
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19043 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: D:/soft/VisualStudio/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe 
      Build flags: /DWIN32;/D_WINDOWS;/W3
      Id flags:  
      
      The output was:
      0
      Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.29.30136 для x64
      (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.29.30136.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        F:/github/freakworld-githubt/cmake-build-debug/CMakeFiles/3.26.3/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Примечание: включение файла:  F:\\github\\freakworld-githubt\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Примечание: включение файла:  "
  -
    kind: "message-v1"
    backtrace:
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: D:/soft/VisualStudio/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe 
      Build flags: /DWIN32;/D_WINDOWS;/W3;/GR;/EHsc
      Id flags:  
      
      The output was:
      0
      Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.29.30136 для x64
      (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.29.30136.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        F:/github/freakworld-githubt/cmake-build-debug/CMakeFiles/3.26.3/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Примечание: включение файла:  F:\\github\\freakworld-githubt\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Примечание: включение файла:  "
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "F:/github/freakworld-githubt/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-jui7cn"
      binary: "F:/github/freakworld-githubt/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-jui7cn"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "F:/github/vcpkg"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: F:/github/freakworld-githubt/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-jui7cn
        
        Run Build Command(s):D:/soft/CLion 2020.2.5/bin/cmake/win/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_57602\\fast && 	D:\\soft\\VisualStudio\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\nmake.exe  -f CMakeFiles\\cmTC_57602.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_57602.dir\\build
        Building C object CMakeFiles/cmTC_57602.dir/CMakeCCompilerABI.c.obj
        	"D:\\soft\\CLion 2020.2.5\\bin\\cmake\\win\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_57602.dir\\CMakeCCompilerABI.c.obj.d --working-dir=F:\\github\\freakworld-githubt\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-jui7cn --filter-prefix="╧Ёшьхўрэшх: тъы■ўхэшх Їрщыр:  " -- D:\\soft\\VisualStudio\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe @F:\\TEMP\\nmB61A.tmp
        CMakeCCompilerABI.c
        Linking C executable cmTC_57602.exe
        	"D:\\soft\\CLion 2020.2.5\\bin\\cmake\\win\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_57602.dir --rc="D:\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe" --mt="D:\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\mt.exe" --manifests -- D:\\soft\\VisualStudio\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_57602.dir\\objects1.rsp @F:\\TEMP\\nmB64A.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_57602.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_57602.dir/embed.manifest
        RC Pass 1:
        D:\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_57602.dir/manifest.res CMakeFiles\\cmTC_57602.dir/manifest.rc
        LINK Pass 1:
        D:\\soft\\VisualStudio\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_57602.dir\\objects1.rsp /out:cmTC_57602.exe /implib:cmTC_57602.lib /pdb:F:\\github\\freakworld-githubt\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-jui7cn\\cmTC_57602.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_57602.dir/intermediate.manifest CMakeFiles\\cmTC_57602.dir/manifest.res
        MT:
        D:\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_57602.dir/intermediate.manifest /out:CMakeFiles\\cmTC_57602.dir/embed.manifest /notify_update
        RC Pass 2:
        D:\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_57602.dir/manifest.res CMakeFiles\\cmTC_57602.dir/manifest.rc
        FINAL LINK:
        D:\\soft\\VisualStudio\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_57602.dir\\objects1.rsp /out:cmTC_57602.exe /implib:cmTC_57602.lib /pdb:F:\\github\\freakworld-githubt\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-jui7cn\\cmTC_57602.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_57602.dir/intermediate.manifest CMakeFiles\\cmTC_57602.dir/manifest.res
        	C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -executionpolicy Bypass -file F:/github/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary F:/github/freakworld-githubt/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-jui7cn/cmTC_57602.exe -installedDir F:/github/vcpkg/installed/x64-windows/debug/bin -OutVariable out
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/soft/CLion 2020.2.5/bin/cmake/win/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "F:/github/freakworld-githubt/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-pmfiy0"
      binary: "F:/github/freakworld-githubt/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-pmfiy0"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "F:/github/vcpkg"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: F:/github/freakworld-githubt/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-pmfiy0
        
        Run Build Command(s):D:/soft/CLion 2020.2.5/bin/cmake/win/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_167e6\\fast && 	D:\\soft\\VisualStudio\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\nmake.exe  -f CMakeFiles\\cmTC_167e6.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_167e6.dir\\build
        Building CXX object CMakeFiles/cmTC_167e6.dir/CMakeCXXCompilerABI.cpp.obj
        	"D:\\soft\\CLion 2020.2.5\\bin\\cmake\\win\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_167e6.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir=F:\\github\\freakworld-githubt\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-pmfiy0 --filter-prefix="╧Ёшьхўрэшх: тъы■ўхэшх Їрщыр:  " -- D:\\soft\\VisualStudio\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe @F:\\TEMP\\nmB946.tmp
        CMakeCXXCompilerABI.cpp
        Linking CXX executable cmTC_167e6.exe
        	"D:\\soft\\CLion 2020.2.5\\bin\\cmake\\win\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_167e6.dir --rc="D:\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe" --mt="D:\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\mt.exe" --manifests -- D:\\soft\\VisualStudio\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_167e6.dir\\objects1.rsp @F:\\TEMP\\nmB986.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_167e6.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_167e6.dir/embed.manifest
        RC Pass 1:
        D:\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_167e6.dir/manifest.res CMakeFiles\\cmTC_167e6.dir/manifest.rc
        LINK Pass 1:
        D:\\soft\\VisualStudio\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_167e6.dir\\objects1.rsp /out:cmTC_167e6.exe /implib:cmTC_167e6.lib /pdb:F:\\github\\freakworld-githubt\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-pmfiy0\\cmTC_167e6.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_167e6.dir/intermediate.manifest CMakeFiles\\cmTC_167e6.dir/manifest.res
        MT:
        D:\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_167e6.dir/intermediate.manifest /out:CMakeFiles\\cmTC_167e6.dir/embed.manifest /notify_update
        RC Pass 2:
        D:\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_167e6.dir/manifest.res CMakeFiles\\cmTC_167e6.dir/manifest.rc
        FINAL LINK:
        D:\\soft\\VisualStudio\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_167e6.dir\\objects1.rsp /out:cmTC_167e6.exe /implib:cmTC_167e6.lib /pdb:F:\\github\\freakworld-githubt\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-pmfiy0\\cmTC_167e6.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_167e6.dir/intermediate.manifest CMakeFiles\\cmTC_167e6.dir/manifest.res
        	C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -executionpolicy Bypass -file F:/github/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary F:/github/freakworld-githubt/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-pmfiy0/cmTC_167e6.exe -installedDir F:/github/vcpkg/installed/x64-windows/debug/bin -OutVariable out
        
      exitCode: 0
...
